drop table  IF EXISTS Genres CASCADE;
drop table  IF EXISTS Genres_line CASCADE;
drop table  IF EXISTS Rating CASCADE;
drop table  IF EXISTS Status CASCADE;
drop table  IF EXISTS Status_line CASCADE;
drop table  IF EXISTS Frends_line CASCADE;
drop table  IF EXISTS Users CASCADE;
drop table  IF EXISTS Film CASCADE;
drop table  IF EXISTS Likes_line CASCADE;


CREATE TABLE Film (
        Film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Name varchar(40) NOT NULL,
        Description varchar(40) NOT NULL,
        Realise_date date NOT NULL,
        Duration integer NOT NULL,
        Rating_id integer,
        CONSTRAINT constr_date CHECK (Realise_date > '1895-12-28'),
        CONSTRAINT bad_name CHECK (Name <> '')
);

CREATE TABLE Genres_line (
        Genres_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Film_id integer NOT NULL REFERENCES Film (Film_id),
		Genre_id integer
);

CREATE TABLE Genres (
        Genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Genre varchar(40) NOT NULL
);

ALTER TABLE GENRES_LINE ADD CONSTRAINT fk_genres FOREIGN KEY (Genre_id) REFERENCES Genres;

CREATE TABLE Rating (
        Rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Rating_name varchar(40) NOT NULL
);

ALTER TABLE Film ADD CONSTRAINT fk_rating FOREIGN KEY (Rating_id) REFERENCES Rating;

CREATE TABLE Users (
        User_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Name varchar(40) NOT NULL,
        Login varchar(40) NOT NULL,
        Email varchar(40) NOT NULL,
        Birthday date NOT NULL,
        CONSTRAINT bad_email  CHECK (Email LIKE '%___@___%.__%')
);


CREATE TABLE Frends_line (
        Frends_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        User_id integer NOT NULL REFERENCES Users (User_id),
		User_friend_id integer NOT NULL,
		Status_id integer NOT NULL
);


CREATE TABLE Status (
        Status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Status_name varchar(40) NOT NULL
);

ALTER TABLE Frends_line ADD CONSTRAINT fl_status FOREIGN KEY (Status_id) REFERENCES Status;

ALTER TABLE Frends_line
ALTER Status_id SET DEFAULT 2;


CREATE TABLE Likes_line (
        Status_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Film_id integer NOT NULL REFERENCES Film (Film_id),
		User_id integer NOT NULL REFERENCES Users (User_id)
);